# generated by Gemini AI
from flask import Flask, request, render_template

from multillm import run_comparison
from config import configure

configure()

app = Flask(__name__)

@app.route("/", methods=["GET", "POST"])
async def index():
    if request.method == "POST":
        input_text = request.form["text_input"]  # Get the text from the form
        response_lines = await process_text(input_text) # process the text
        return render_template("index.html", response=response_lines) # Render the HTML page
    return render_template("index.html") # renders the page on a GET request


async def process_text(text):
  result = await run_comparison(text, "n-way")
  if True: return result
  return [f"You entered: '{text}'.", "Here's another line of text!", "And another!"]

if __name__ == "__main__":
    app.run(debug=False)
